# -*- coding: utf-8 -*-
"""28 june

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JypubLpGZZlWPg06N-fFhTzrSdjBTQEW
"""

a = 20
b = 30
print("Before swap ",a,b)
a = a+b
b= a-b
a = a-b
print("After swap",a,b)

def Hcf(x,y):
    if(x>=y):
        check = x
    else:
        check= y
    while(check%x != 0 or check%y != 0):
        check +=1
    return check

x = int(input("Enter x:"))
y = int(input("Enter y:"))
print("HCF : ",Hcf(x,y))

def lcm(x,y):
    if(x>=y):
        check = y
    else:
        check= x
    while(x%check != 0 or y%check != 0):
        check -=1
    return check

x = int(input("Enter x:"))
y = int(input("Enter y:"))
print("LCM: ",lcm(x,y))