# -*- coding: utf-8 -*-
"""assignment 26june

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-1vl6Sg92xUmtO3KAyFNYq0jDDyhxSK0
"""

setA = {10,20,30}
setB = {30,40,50}
print(setA.difference(setB))
print(setB.difference(setA))

setA = {10,20,30}
setB = {30,40,50}
setC = {10,20,30,40,50}
print(setC.issuperset(setA))
print(setC.issuperset(setB))

setA = {10,20,30}
setB = {60,40,50}
setC = {10,20}
print(setB.isdisjoint(setA))
print(setC.isdisjoint(setB))

setA = {10,5,20,30}
setB = {30,40,50}
setC = {10,20}
setA.symmetric_difference_update(setB)
print(setA)
print(setC.symmetric_difference(setB))

row = int(input("Enter a number of row"))
for i in range(0,row):
    for j in range(0,i+1):
        print("*",end="")
    print("")
for i in range(0,row):
    for j in range(0,row-i-1):
        print("*",end="")
    print("")

row = int(input("Enter a number of row"))
for i in range(0,row):
    for j in range(0,row):
        if(i ==row-1 or i == 0 or j==row-1 or j==0):
            print("*",end="")
        else:
             print(" ",end="")
    print("")

row = int(input("Enter a number of row"))
for i in range(0,row):
    print(i+1)
    for j in range(0,i+1):
        print("*",end="")
    print("")

row = int(input("Enter a number of row"))
for i in range(1,row+1):
    print(i,end="")
    for j in range(1,(i*i)+1):
        print("*",end="")
    print("")